apiVersion: v1
kind: Secret
metadata:
  name: amr-slowquery-shared
type: Opaque
stringData:
  POLL_INTERVAL_SECONDS: "${POLL_INTERVAL_SECONDS}"
  SLOWLOG_BATCH_SIZE: "${SLOWLOG_BATCH_SIZE}"
  DCE_ENDPOINT: "${DCE_ENDPOINT}"
  DCR_RULE_ID: "${DCR_RULE_ID}"
